version: '3.7'

networks:
  news-network:

services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - php-fpm
    networks:
      - news-network
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    volumes:
      - ./:/var/www
    networks:
      - news-network
  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    volumes:
      - ./:/var/www
    networks:
      - news-network
    tty: true
  mysql:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      volumes:
          - ./storage/docker/mysql:/var/lib/mysql
      environment:
          - "MYSQL_ROOT_PASSWORD=secret"
          - "MYSQL_USER=news_user"
          - "MYSQL_PASSWORD=secret"
          - "MYSQL_DATABASE=news_db"
      ports:
          - "3306:3306"
      networks:
         news-network:
            aliases:
              - mysql

